import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060d20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3e",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394e",
        "background": "#0b1326",
        "on-background": "#dbe2fd",
        "on-surface": "#dbe2fd",
        "on-surface-variant": "#c4c6d0",
        "primary": "#d8e2ff",
        "primary-container": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#122f5f",
        "on-primary-container": "#385283",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#2c4677",
        "inverse-primary": "#455e90",
        "secondary": "#4edea3",
        "secondary-container": "#00b47d",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-secondary-container": "#003e28",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#dae2fc",
        "tertiary-container": "#bec6e0",
        "tertiary-fixed": "#dae2fc",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary": "#283044",
        "on-tertiary-container": "#4a5268",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465b",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8e909a",
        "outline-variant": "#44474f",
        "inverse-surface": "#dbe2fd",
        "inverse-on-surface": "#283044",
        "surface-tint": "#adc6ff",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        "shimmer": "shimmer 2s linear infinite",
        "blink": "blink 1s step-end infinite",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 15px rgba(78,222,163,0.3)" },
          "50%": { boxShadow: "0 0 35px rgba(78,222,163,0.6)" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
