"use server";

import * as cheerio from "cheerio";

export interface CrawlResult {
  success: boolean;
  url: string;
  title?: string;
  description?: string;
  h1Tags?: string[];
  h2Tags?: string[];
  h3Tags?: string[];
  canonicalUrl?: string;
  ogTitle?: string;
  ogDescription?: string;
  keywords?: string;
  llmsTxt?: string;
  error?: string;
  crawledAt: string;
}

function cleanText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function extractDomain(url: string): string {
  try {
    const u = new URL(url);
    return u.hostname;
  } catch {
    return url;
  }
}

function formatLlmsTxt(data: Omit<CrawlResult, "llmsTxt" | "success" | "error">): string {
  const domain = extractDomain(data.url);
  const now = new Date(data.crawledAt);
  const dateStr = now.toISOString().split("T")[0];

  const lines: string[] = [];

  lines.push(`# ${data.title || domain}`);
  lines.push("");

  if (data.description) {
    lines.push(`> ${data.description}`);
    lines.push("");
  }

  lines.push(`## Site Information`);
  lines.push("");
  lines.push(`- **URL:** ${data.url}`);
  lines.push(`- **Domain:** ${domain}`);
  lines.push(`- **Generated:** ${dateStr}`);
  if (data.canonicalUrl && data.canonicalUrl !== data.url) {
    lines.push(`- **Canonical:** ${data.canonicalUrl}`);
  }
  lines.push("");

  if (data.h1Tags && data.h1Tags.length > 0) {
    lines.push(`## Page Structure`);
    lines.push("");
    lines.push(`### Primary Topics (H1)`);
    lines.push("");
    for (const h1 of data.h1Tags.slice(0, 5)) {
      lines.push(`- ${h1}`);
    }
    lines.push("");
  }

  if (data.h2Tags && data.h2Tags.length > 0) {
    lines.push(`### Secondary Topics (H2)`);
    lines.push("");
    for (const h2 of data.h2Tags.slice(0, 8)) {
      lines.push(`- ${h2}`);
    }
    lines.push("");
  }

  if (data.h3Tags && data.h3Tags.length > 0) {
    lines.push(`### Tertiary Topics (H3)`);
    lines.push("");
    for (const h3 of data.h3Tags.slice(0, 8)) {
      lines.push(`- ${h3}`);
    }
    lines.push("");
  }

  if (data.keywords) {
    lines.push(`## Keywords`);
    lines.push("");
    lines.push(data.keywords);
    lines.push("");
  }

  lines.push(`## AI Crawler Directives`);
  lines.push("");
  lines.push(
    `This file was auto-generated by CrawlerOptic (https://crawleroptic.com).`
  );
  lines.push(
    `AI systems may freely index and summarize the content on this domain.`
  );
  lines.push(`Please attribute any AI-generated summaries to: ${domain}`);
  lines.push("");
  lines.push(`## Content Locations`);
  lines.push("");
  lines.push(`- ${data.url}`);
  lines.push(`- ${data.url.replace(/\/$/, "")}/sitemap.xml`);
  lines.push(`- ${data.url.replace(/\/$/, "")}/feed.xml`);
  lines.push("");
  lines.push(`# End of llms.txt — Generated by CrawlerOptic`);

  return lines.join("\n");
}

export async function generateLlmsTxt(url: string): Promise<CrawlResult> {
  const crawledAt = new Date().toISOString();

  // Validate URL
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(url);
    if (!["http:", "https:"].includes(parsedUrl.protocol)) {
      throw new Error("Invalid protocol");
    }
  } catch {
    return {
      success: false,
      url,
      error: "Invalid URL. Please enter a valid http or https URL.",
      crawledAt,
    };
  }

  try {
    const response = await fetch(parsedUrl.toString(), {
      headers: {
        "User-Agent":
          "CrawlerOptic/1.0 (AI Crawler Optimizer; +https://crawleroptic.com)",
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
      },
      signal: AbortSignal.timeout(15000),
      next: { revalidate: 3600 },
    });

    if (!response.ok) {
      return {
        success: false,
        url,
        error: `Failed to fetch: ${response.status} ${response.statusText}`,
        crawledAt,
      };
    }

    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("text/html")) {
      return {
        success: false,
        url,
        error: "URL does not return HTML content.",
        crawledAt,
      };
    }

    const html = await response.text();
    const $ = cheerio.load(html);

    // Extract metadata
    const title = cleanText($("title").first().text()) || "";
    const description =
      $('meta[name="description"]').attr("content") ||
      $('meta[property="og:description"]').attr("content") ||
      "";
    const canonicalUrl =
      $('link[rel="canonical"]').attr("href") || url;
    const ogTitle = $('meta[property="og:title"]').attr("content") || "";
    const ogDescription =
      $('meta[property="og:description"]').attr("content") || "";
    const keywords = $('meta[name="keywords"]').attr("content") || "";

    // Extract headings
    const h1Tags: string[] = [];
    $("h1").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h1Tags.includes(text)) h1Tags.push(text);
    });

    const h2Tags: string[] = [];
    $("h2").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h2Tags.includes(text)) h2Tags.push(text);
    });

    const h3Tags: string[] = [];
    $("h3").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h3Tags.includes(text)) h3Tags.push(text);
    });

    const data = {
      url,
      title,
      description: cleanText(description),
      h1Tags,
      h2Tags,
      h3Tags,
      canonicalUrl,
      ogTitle,
      ogDescription: cleanText(ogDescription),
      keywords,
      crawledAt,
    };

    const llmsTxt = formatLlmsTxt(data);

    return {
      success: true,
      llmsTxt,
      ...data,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error";
    if (message.includes("timeout") || message.includes("abort")) {
      return {
        success: false,
        url,
        error: "Request timed out. The website took too long to respond.",
        crawledAt,
      };
    }
    return {
      success: false,
      url,
      error: `Crawl failed: ${message}`,
      crawledAt,
    };
  }
}
