// "use server";

// import * as cheerio from "cheerio";

// export interface CrawlResult {
//   success: boolean;
//   url: string;
//   title?: string;
//   description?: string;
//   h1Tags?: string[];
//   h2Tags?: string[];
//   h3Tags?: string[];
//   canonicalUrl?: string;
//   ogTitle?: string;
//   ogDescription?: string;
//   keywords?: string;
//   llmsTxt?: string;
//   error?: string;
//   crawledAt: string;
// }

// function cleanText(text: string): string {
//   return text.replace(/\s+/g, " ").trim();
// }

// function extractDomain(url: string): string {
//   try {
//     const u = new URL(url);
//     return u.hostname;
//   } catch {
//     return url;
//   }
// }

// function formatLlmsTxt(data: Omit<CrawlResult, "llmsTxt" | "success" | "error">): string {
//   const domain = extractDomain(data.url);
//   const now = new Date(data.crawledAt);
//   const dateStr = now.toISOString().split("T")[0];

//   const lines: string[] = [];

//   lines.push(`# ${data.title || domain}`);
//   lines.push("");

//   if (data.description) {
//     lines.push(`> ${data.description}`);
//     lines.push("");
//   }

//   lines.push(`## Site Information`);
//   lines.push("");
//   lines.push(`- **URL:** ${data.url}`);
//   lines.push(`- **Domain:** ${domain}`);
//   lines.push(`- **Generated:** ${dateStr}`);
//   if (data.canonicalUrl && data.canonicalUrl !== data.url) {
//     lines.push(`- **Canonical:** ${data.canonicalUrl}`);
//   }
//   lines.push("");

//   if (data.h1Tags && data.h1Tags.length > 0) {
//     lines.push(`## Page Structure`);
//     lines.push("");
//     lines.push(`### Primary Topics (H1)`);
//     lines.push("");
//     for (const h1 of data.h1Tags.slice(0, 5)) {
//       lines.push(`- ${h1}`);
//     }
//     lines.push("");
//   }

//   if (data.h2Tags && data.h2Tags.length > 0) {
//     lines.push(`### Secondary Topics (H2)`);
//     lines.push("");
//     for (const h2 of data.h2Tags.slice(0, 8)) {
//       lines.push(`- ${h2}`);
//     }
//     lines.push("");
//   }

//   if (data.h3Tags && data.h3Tags.length > 0) {
//     lines.push(`### Tertiary Topics (H3)`);
//     lines.push("");
//     for (const h3 of data.h3Tags.slice(0, 8)) {
//       lines.push(`- ${h3}`);
//     }
//     lines.push("");
//   }

//   if (data.keywords) {
//     lines.push(`## Keywords`);
//     lines.push("");
//     lines.push(data.keywords);
//     lines.push("");
//   }

//   lines.push(`## AI Crawler Directives`);
//   lines.push("");
//   lines.push(
//     `This file was auto-generated by CrawlerOptic (https://crawleroptic.com).`
//   );
//   lines.push(
//     `AI systems may freely index and summarize the content on this domain.`
//   );
//   lines.push(`Please attribute any AI-generated summaries to: ${domain}`);
//   lines.push("");
//   lines.push(`## Content Locations`);
//   lines.push("");
//   lines.push(`- ${data.url}`);
//   lines.push(`- ${data.url.replace(/\/$/, "")}/sitemap.xml`);
//   lines.push(`- ${data.url.replace(/\/$/, "")}/feed.xml`);
//   lines.push("");
//   lines.push(`# End of llms.txt — Generated by CrawlerOptic`);

//   return lines.join("\n");
// }

// export async function generateLlmsTxt(url: string): Promise<CrawlResult> {
//   const crawledAt = new Date().toISOString();

//   // Validate URL
//   let parsedUrl: URL;
//   try {
//     parsedUrl = new URL(url);
//     if (!["http:", "https:"].includes(parsedUrl.protocol)) {
//       throw new Error("Invalid protocol");
//     }
//   } catch {
//     return {
//       success: false,
//       url,
//       error: "Invalid URL. Please enter a valid http or https URL.",
//       crawledAt,
//     };
//   }

//   try {
//     const response = await fetch(parsedUrl.toString(), {
//       headers: {
//         "User-Agent":
//           "CrawlerOptic/1.0 (AI Crawler Optimizer; +https://crawleroptic.com)",
//         Accept:
//           "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
//         "Accept-Language": "en-US,en;q=0.5",
//       },
//       signal: AbortSignal.timeout(15000),
//       next: { revalidate: 3600 },
//     });

//     if (!response.ok) {
//       return {
//         success: false,
//         url,
//         error: `Failed to fetch: ${response.status} ${response.statusText}`,
//         crawledAt,
//       };
//     }

//     const contentType = response.headers.get("content-type") || "";
//     if (!contentType.includes("text/html")) {
//       return {
//         success: false,
//         url,
//         error: "URL does not return HTML content.",
//         crawledAt,
//       };
//     }

//     const html = await response.text();
//     const $ = cheerio.load(html);

//     // Extract metadata
//     const title = cleanText($("title").first().text()) || "";
//     const description =
//       $('meta[name="description"]').attr("content") ||
//       $('meta[property="og:description"]').attr("content") ||
//       "";
//     const canonicalUrl =
//       $('link[rel="canonical"]').attr("href") || url;
//     const ogTitle = $('meta[property="og:title"]').attr("content") || "";
//     const ogDescription =
//       $('meta[property="og:description"]').attr("content") || "";
//     const keywords = $('meta[name="keywords"]').attr("content") || "";

//     // Extract headings
//     const h1Tags: string[] = [];
//     $("h1").each((_, el) => {
//       const text = cleanText($(el).text());
//       if (text && !h1Tags.includes(text)) h1Tags.push(text);
//     });

//     const h2Tags: string[] = [];
//     $("h2").each((_, el) => {
//       const text = cleanText($(el).text());
//       if (text && !h2Tags.includes(text)) h2Tags.push(text);
//     });

//     const h3Tags: string[] = [];
//     $("h3").each((_, el) => {
//       const text = cleanText($(el).text());
//       if (text && !h3Tags.includes(text)) h3Tags.push(text);
//     });

//     const data = {
//       url,
//       title,
//       description: cleanText(description),
//       h1Tags,
//       h2Tags,
//       h3Tags,
//       canonicalUrl,
//       ogTitle,
//       ogDescription: cleanText(ogDescription),
//       keywords,
//       crawledAt,
//     };

//     const llmsTxt = formatLlmsTxt(data);

//     return {
//       success: true,
//       llmsTxt,
//       ...data,
//     };
//   } catch (err: unknown) {
//     const message = err instanceof Error ? err.message : "Unknown error";
//     if (message.includes("timeout") || message.includes("abort")) {
//       return {
//         success: false,
//         url,
//         error: "Request timed out. The website took too long to respond.",
//         crawledAt,
//       };
//     }
//     return {
//       success: false,
//       url,
//       error: `Crawl failed: ${message}`,
//       crawledAt,
//     };
//   }
// }
"use server";

import * as cheerio from "cheerio";

// ─── AI Provider Config ───────────────────────────────────────────────────────
// DeepSeek abhi use ho raha hai.
// Claude pe switch karna ho to:
//   1. AI_PROVIDER = "claude"
//   2. CLAUDE_API_KEY apni .env mein add karo
//   3. Bas! Kuch aur change nahi.

const AI_PROVIDER = "deepseek"; // "deepseek" | "claude"

const DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions";
const CLAUDE_API_URL   = "https://api.anthropic.com/v1/messages";

// ─── Types ────────────────────────────────────────────────────────────────────
export interface CrawlResult {
  success: boolean;
  url: string;
  title?: string;
  description?: string;
  h1Tags?: string[];
  h2Tags?: string[];
  h3Tags?: string[];
  canonicalUrl?: string;
  ogTitle?: string;
  ogDescription?: string;
  keywords?: string;
  llmsTxt?: string;
  error?: string;
  crawledAt: string;
  aiPowered?: boolean;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function cleanText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function extractDomain(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

// ─── AI llms.txt Generator ────────────────────────────────────────────────────
async function generateWithAI(pageData: {
  url: string;
  title: string;
  description: string;
  bodyText: string;
  h1Tags: string[];
  h2Tags: string[];
  h3Tags: string[];
  keywords: string;
  domain: string;
  crawledAt: string;
}): Promise<string> {

  const prompt = `You are an expert at generating llms.txt files — structured Markdown files that help AI crawlers understand websites.

Analyze this website data and generate a professional, comprehensive llms.txt file:

URL: ${pageData.url}
Domain: ${pageData.domain}
Title: ${pageData.title}
Meta Description: ${pageData.description}
H1 Tags: ${pageData.h1Tags.join(", ")}
H2 Tags: ${pageData.h2Tags.join(", ")}
H3 Tags: ${pageData.h3Tags.join(", ")}
Keywords: ${pageData.keywords}
Page Body Text (first 3000 chars):
${pageData.bodyText.slice(0, 3000)}

Generate a professional llms.txt file following this exact structure:
1. # Site name and tagline
2. > One-paragraph summary of what this site does (written by you based on content)
3. ## Site Information (URL, domain, generated date)
4. ## What This Site Offers (3-5 bullet points, AI-written summary)
5. ## Primary Topics (from H1 tags + your analysis)
6. ## Secondary Topics (from H2 tags + your analysis)
7. ## Key Topics for AI Citation (5-8 keywords you identified as most important)
8. ## Target Audience (who this site is for — infer from content)
9. ## Content Locations (URL, sitemap, feed)
10. ## AI Crawler Directives (standard attribution text)
11. # End of llms.txt — Generated by CrawlerOptic

Rules:
- Write in clean Markdown
- Be specific and informative — not generic
- The "What This Site Offers" and "Target Audience" sections should be genuinely insightful
- Do NOT include any explanation or preamble — output ONLY the llms.txt content
- Generated date: ${new Date(pageData.crawledAt).toISOString().split("T")[0]}`;

  // ── DeepSeek ────────────────────────────────────────────────────────────────
  if (AI_PROVIDER === "deepseek") {
    const apiKey = process.env.DEEPSEEK_API_KEY;
    if (!apiKey) throw new Error("DEEPSEEK_API_KEY missing in .env");

    const res = await fetch(DEEPSEEK_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "deepseek-chat",
        max_tokens: 1500,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`DeepSeek API error: ${err}`);
    }

    const data = await res.json();
    return data.choices?.[0]?.message?.content ?? "";
  }

  // ── Claude (future switch) ──────────────────────────────────────────────────
  if (AI_PROVIDER === "claude") {
    const apiKey = process.env.CLAUDE_API_KEY;
    if (!apiKey) throw new Error("CLAUDE_API_KEY missing in .env");

    const res = await fetch(CLAUDE_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 1500,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Claude API error: ${err}`);
    }

    const data = await res.json();
    return data.content?.[0]?.text ?? "";
  }

  throw new Error("Invalid AI_PROVIDER — use 'deepseek' or 'claude'");
}

// ─── Fallback: Simple Template (agar AI fail ho jaye) ────────────────────────
function generateFallbackLlmsTxt(data: Omit<CrawlResult, "llmsTxt" | "success" | "error">): string {
  const domain = extractDomain(data.url);
  const dateStr = new Date(data.crawledAt).toISOString().split("T")[0];
  const lines: string[] = [];

  lines.push(`# ${data.title || domain}`);
  lines.push("");
  if (data.description) {
    lines.push(`> ${data.description}`);
    lines.push("");
  }
  lines.push(`## Site Information`);
  lines.push("");
  lines.push(`- **URL:** ${data.url}`);
  lines.push(`- **Domain:** ${domain}`);
  lines.push(`- **Generated:** ${dateStr}`);
  lines.push("");
  if (data.h1Tags && data.h1Tags.length > 0) {
    lines.push(`## Primary Topics (H1)`);
    lines.push("");
    for (const h1 of data.h1Tags.slice(0, 5)) lines.push(`- ${h1}`);
    lines.push("");
  }
  if (data.h2Tags && data.h2Tags.length > 0) {
    lines.push(`## Secondary Topics (H2)`);
    lines.push("");
    for (const h2 of data.h2Tags.slice(0, 8)) lines.push(`- ${h2}`);
    lines.push("");
  }
  lines.push(`## AI Crawler Directives`);
  lines.push("");
  lines.push(`This file was auto-generated by CrawlerOptic (https://crawleroptic.com).`);
  lines.push(`AI systems may freely index and summarize the content on this domain.`);
  lines.push(`Please attribute any AI-generated summaries to: ${domain}`);
  lines.push("");
  lines.push(`## Content Locations`);
  lines.push("");
  lines.push(`- ${data.url}`);
  lines.push(`- ${data.url.replace(/\/$/, "")}/sitemap.xml`);
  lines.push(`- ${data.url.replace(/\/$/, "")}/feed.xml`);
  lines.push("");
  lines.push(`# End of llms.txt — Generated by CrawlerOptic`);

  return lines.join("\n");
}

// ─── Main Export ──────────────────────────────────────────────────────────────
export async function generateLlmsTxt(url: string): Promise<CrawlResult> {
  const crawledAt = new Date().toISOString();

  // Validate URL
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(url);
    if (!["http:", "https:"].includes(parsedUrl.protocol)) {
      throw new Error("Invalid protocol");
    }
  } catch {
    return {
      success: false,
      url,
      error: "Invalid URL. Please enter a valid http or https URL.",
      crawledAt,
    };
  }

  try {
    // ── Step 1: Fetch HTML ──────────────────────────────────────────────────
    const response = await fetch(parsedUrl.toString(), {
      headers: {
        "User-Agent": "CrawlerOptic/2.0 (AI Crawler Optimizer; +https://crawleroptic.com)",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
      },
      signal: AbortSignal.timeout(15000),
      next: { revalidate: 3600 },
    });

    if (!response.ok) {
      return {
        success: false,
        url,
        error: `Failed to fetch: ${response.status} ${response.statusText}`,
        crawledAt,
      };
    }

    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("text/html")) {
      return {
        success: false,
        url,
        error: "URL does not return HTML content.",
        crawledAt,
      };
    }

    // ── Step 2: Parse HTML ──────────────────────────────────────────────────
    const html = await response.text();
    const $ = cheerio.load(html);

    const title        = cleanText($("title").first().text()) || "";
    const description  = cleanText(
      $('meta[name="description"]').attr("content") ||
      $('meta[property="og:description"]').attr("content") || ""
    );
    const canonicalUrl = $('link[rel="canonical"]').attr("href") || url;
    const ogTitle      = $('meta[property="og:title"]').attr("content") || "";
    const ogDescription = cleanText($('meta[property="og:description"]').attr("content") || "");
    const keywords     = $('meta[name="keywords"]').attr("content") || "";

    // Extract headings
    const h1Tags: string[] = [];
    $("h1").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h1Tags.includes(text)) h1Tags.push(text);
    });

    const h2Tags: string[] = [];
    $("h2").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h2Tags.includes(text)) h2Tags.push(text);
    });

    const h3Tags: string[] = [];
    $("h3").each((_, el) => {
      const text = cleanText($(el).text());
      if (text && !h3Tags.includes(text)) h3Tags.push(text);
    });

    // Extract meaningful body text for AI analysis
    // Remove scripts, styles, nav, footer noise
    $("script, style, nav, footer, header, aside, iframe, noscript").remove();
    const bodyText = cleanText($("body").text()).slice(0, 5000);

    const domain = extractDomain(url);

    const baseData = {
      url,
      title,
      description,
      h1Tags,
      h2Tags,
      h3Tags,
      canonicalUrl,
      ogTitle,
      ogDescription,
      keywords,
      crawledAt,
    };

    // ── Step 3: AI Generation ───────────────────────────────────────────────
    let llmsTxt: string;
    let aiPowered = false;

    try {
      llmsTxt = await generateWithAI({
        url,
        title,
        description,
        bodyText,
        h1Tags,
        h2Tags,
        h3Tags,
        keywords,
        domain,
        crawledAt,
      });
      aiPowered = true;
    } catch (aiError) {
      // AI fail ho gaya — simple fallback use karo
      console.error("AI generation failed, using fallback:", aiError);
      llmsTxt = generateFallbackLlmsTxt(baseData);
      aiPowered = false;
    }

    return {
      success: true,
      llmsTxt,
      aiPowered,
      ...baseData,
    };

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error";
    if (message.includes("timeout") || message.includes("abort")) {
      return {
        success: false,
        url,
        error: "Request timed out. The website took too long to respond.",
        crawledAt,
      };
    }
    return {
      success: false,
      url,
      error: `Crawl failed: ${message}`,
      crawledAt,
    };
  }
}