import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "CrawlerOptic Terms of Service — the rules and conditions for using our platform.",
};

const LAST_UPDATED = "March 1, 2026";
const COMPANY = "CrawlerOptic";
const CONTACT_EMAIL = "legal@crawleroptic.com";
const SITE_URL = "https://crawleroptic.com";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 pb-16 px-6 max-w-4xl mx-auto">
        <div className="py-12 border-b border-outline-variant/10 mb-10">
          <span className="text-[10px] uppercase tracking-widest text-secondary font-label block mb-3">
            Legal
          </span>
          <h1 className="text-4xl font-black tracking-[-0.04em] text-on-surface mb-3">
            Terms of Service
          </h1>
          <p className="text-on-surface-variant">
            Last updated: <span className="text-on-surface">{LAST_UPDATED}</span>
          </p>
        </div>

        <div className="blog-prose">
          <p>
            Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully
            before using {SITE_URL} (the &ldquo;Service&rdquo;) operated by{" "}
            {COMPANY} (&ldquo;us,&rdquo; &ldquo;we,&rdquo; or
            &ldquo;our&rdquo;).
          </p>
          <p>
            By accessing or using the Service, you agree to be bound by these
            Terms. If you disagree with any part of the Terms, you may not
            access the Service.
          </p>

          <h2>1. Use of the Service</h2>

          <h3>Permitted Use</h3>
          <p>
            You may use the Service to analyze publicly accessible websites and
            generate <code>llms.txt</code> files for your own or your
            clients&apos; domains. The Service is intended for legitimate web
            optimization purposes.
          </p>

          <h3>Prohibited Use</h3>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>
              Crawl websites for which you do not have authorization to access
            </li>
            <li>Engage in any activity that violates applicable laws</li>
            <li>
              Attempt to gain unauthorized access to any systems or networks
            </li>
            <li>
              Conduct denial-of-service attacks or overload our infrastructure
            </li>
            <li>
              Scrape, harvest, or extract data from the Service beyond its
              intended functionality
            </li>
            <li>
              Use automated scripts or bots to access the Service without our
              express written permission
            </li>
            <li>
              Reproduce, duplicate, copy, sell, or resell any portion of the
              Service without express written permission
            </li>
            <li>
              Use the Service for any unlawful purpose or in violation of any
              regulations
            </li>
          </ul>

          <h2>2. Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality
            are and will remain the exclusive property of {COMPANY} and its
            licensors. Our trademarks and trade dress may not be used in
            connection with any product or service without our prior written
            consent.
          </p>
          <p>
            The <code>llms.txt</code> files generated by the Service using your
            website&apos;s content are your property. We claim no ownership
            over generated output that derives from your content.
          </p>

          <h2>3. Disclaimer of Warranties</h2>
          <p>
            The Service is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS
            AVAILABLE&rdquo; basis without any warranties of any kind, either
            express or implied, including but not limited to:
          </p>
          <ul>
            <li>Warranties of merchantability or fitness for a particular purpose</li>
            <li>Warranties that the Service will be uninterrupted or error-free</li>
            <li>
              Warranties as to the accuracy or completeness of any generated
              output
            </li>
            <li>
              Warranties that defects will be corrected or that the Service is
              free of viruses
            </li>
          </ul>
          <p>
            {COMPANY} does not warrant that generated <code>llms.txt</code>{" "}
            files will achieve any specific result with respect to AI crawler
            indexing, citation frequency, or search visibility. Results may
            vary.
          </p>

          <h2>4. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, {COMPANY} shall not be
            liable for any indirect, incidental, special, consequential, or
            punitive damages, including but not limited to loss of profits,
            data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul>
            <li>Your use of or inability to use the Service</li>
            <li>
              Any unauthorized access to or alteration of your transmissions or
              data
            </li>
            <li>Any statements or conduct of any third party on the Service</li>
            <li>Any other matter relating to the Service</li>
          </ul>

          <h2>5. Third-Party Websites</h2>
          <p>
            The Service may contain links to third-party websites or services
            that are not owned or controlled by {COMPANY}. We have no control
            over and assume no responsibility for the content, privacy policies,
            or practices of any third-party websites. We encourage you to review
            the privacy policy and terms of each website you visit.
          </p>

          <h2>6. Rate Limiting and Fair Use</h2>
          <p>
            To ensure fair access for all users, we implement rate limiting on
            URL analysis requests. Excessive use that degrades service quality
            for other users may result in temporary or permanent access
            restrictions. We reserve the right to modify rate limits at any
            time without notice.
          </p>

          <h2>7. Advertising</h2>
          <p>
            The Service displays advertisements served by Google AdSense and
            potentially other advertising networks. By using the Service, you
            consent to the display of such advertisements. We are not
            responsible for the content of advertisements displayed on the
            Service.
          </p>

          <h2>8. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service immediately,
            without prior notice or liability, for any reason, including if you
            breach these Terms. Upon termination, your right to use the Service
            will immediately cease.
          </p>

          <h2>9. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with
            applicable law, without regard to its conflict of law provisions.
            Any disputes arising from these Terms shall be subject to the
            exclusive jurisdiction of the competent courts.
          </p>

          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will
            notify users of material changes by updating the &ldquo;Last
            updated&rdquo; date. Your continued use of the Service after changes
            constitutes acceptance of the revised Terms.
          </p>

          <h2>11. Contact</h2>
          <p>
            If you have questions about these Terms, please contact us:
          </p>
          <p>
            <strong>{COMPANY}</strong>
            <br />
            Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
            <br />
            Website: <a href={SITE_URL}>{SITE_URL}</a>
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
